### PR TITLE
Python 3 compatibility etc

### PR DESCRIPTION
**Pull request by microprediction**
Please don't regard this pull request as a floccinaucinihilipilification of the existing packaging. However, I have: 

- Added /examples
- Added /tests
- Fixed import so package builds
- Moved to Python 3 
- Added data example, though not the best one I admit

Let me know if you want me to push it to PyPI.

### CODE REVIEW

**Comment by microprediction** [comment]
Added picture to README.md

**Comment by saifuddin778** [comment]
Thanks for adding stuff in. Appreciated.

**Comment by microprediction** [comment]
sure, I realize I may have broken python 2. East enough to keep that but do you care?

**Comment by saifuddin778** [comment]
There wasn't anything serious in your changes to break python3, although its a good step to make it compliant on both 2.7 and 3.x platforms.

**Comment by microprediction** [comment]
Oh yeah you are right. I forgot py2 has both xrange and range. It's been so long. So nothing should be broken. You should put this on PyPI! I can add the github action if you want or you could imitate: 

- https://github.com/microprediction/humpday/blob/main/.github/workflows/deploy.yml

**Pull request merged**
